---
- name: Redfish python script test
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Get powerstate
    script: files/GetSetPowerStateREDFISH.py -ip 10.0.0.89 -u root -p r0gerwilc0 --set On
    args:
      executable: python3
    register: results

  - name: display the results
    debug:
      var: results

  
