---
- name: Ansible URI playbook for redfish
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Redfish get test
      uri:
        url: http://localhost:2224/redfish/v1/Systems/437XR1138R2/Processors
        method: GET
      register: redfishresponse

    - name: Display result
      debug:
        var: redfishresponse
